-Added Elephant in the Room (not enabled by default)
-Add buffs and updated broken icons (invisibility, bears, bull's, fox's, eagles', owl's, cat's, slow, shield, shield of faith, bless, combat expertise, charging, total defense, cover, cover partial, flanking, mage armor, heroism, concealment, concealment, total)
